### ISSUE TITLE
ipfs swarms with the same swarm.key

### ISSUE THREAD

**Issue by mariosk** [Kubuxu/go-ipfs-swarm-key-gen#2]
I've setup 2 ipfs daemons with the same ~/.ipfs/swarm.key. I've 2 questions:
1. Should the command "ipfs swarm peers" show 1 result? I now get nothing as a result.
2. I added a file in the first node but I can't see it from the other node.

What am I  missing?
Thanks!

**Comment by Kubuxu** [comment]
IPFS needs a way to bootstrap the network. On public network those are gateways that do this work.
When running private network you need to change bootstrap nodes to your own.

So on both nodes:
```bash
ipfs bootstrap rm --all
ipfs bootstrap add $FULL_ADDRESS_PEERID_OF_THE_OTHER_NODE
```

you can get full address from `ipfs id`.

**Comment by mariosk** [comment]
Thanks a lot @Kubuxu, that works fine!
