### ISSUE TITLE
Proxy / Bridge node using swarm.key

### ISSUE THREAD

**Issue by 0zAND1z** [Kubuxu/go-ipfs-swarm-key-gen#3]
Following up on our conversation from [IPFS Discourse](https://discuss.ipfs.io/t/go-ipfs-swarm-key-discussion/2992) here.

How about creating a Layer-2 alike key management for an IPFS node to bridge the contents between two heterogeneous IPFS cluster having their own respective swarm.keys?

All thoughts & approaches are welcome.

**Comment by machawk1** [comment]
Here is a scenario that would make this ability useful to me:

In [ipwb](https://github.com/oduwsdl/ipwb) I anticipate using IPFS swarms to allow sharing of web archives between a select set of peers. These captures may contain personal/private information that necessitates these capture not being accessible to the whole IPFS network.

The continued privacy of the network's contents relies on protection of this key. However, in the situation where a group (A) wants to proactively share the contents with another private network (B), being able to manage and propagate multiple keys (peers in B become aware of A) for multiple networks from a single perspective (peers in A do not become of B peers) may be useful. 

This may facilitate not just a hierarchy of a peer network with respect to privacy but a directional graph. B may know of {A,B} and C maybe just {C,B} then D can be made aware of any permutation/combination of networks based on a network's members sharing of keys. This may also work on the micro level of having select accessibility within an organization, e.g., Alice, Bob, and Carol are all part of network A and the above is applied.

I am not familiar enough with inner working of IPFS to know how much of this ability already exists in the core protocol.

**Comment by chiragg6** [comment]
Can we use https://github.com/ipfs/js-ipfs/tree/master/examples/circuit-relaying for this purpose?

**Comment by cattitude** [comment]
@Kubuxu , any thoughts on using the Circuit Relay for bridging two different IPFS swarm clusters?

**Comment by Kubuxu** [comment]
It is not possible at the time. I fully understand this would be useful, please raise this issue in https://github.com/libp2p/go-libp2p .

**Comment by 0zAND1z** [comment]
This issue will be moved to libp2p. Thanks for all the inputs!
