### ISSUE TITLE
Longer swarm keys and documentation about swarm in general?

### ISSUE THREAD

**Issue by postables** [Kubuxu/go-ipfs-swarm-key-gen#4]
Is it possible to use swarm keys that are longer in length for better security?

Also is there any documentation, or technical papers on swarm, and the various key formats, etc...

Thanks.

**Comment by kggp1995** [comment]
Longer keys are evidently possible.

Apart from the docs @ experimental features [here](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks), I'm afraid we do not have much. Feel free to PR with a wiki for this repo! I'll help where needed specifically.

(Cc'ing @Kubuxu for ack & comments.)

**Comment by Kubuxu** [comment]
It is currently not possible, swarm key is used as a symmetric key. It is the same length as symmetric key generated after SSL handshake. There isn't really a need for it to be longer.

**Comment by postables** [comment]
Ah okay, thanks for this.
